name: Build

on:
  push:
    tags:
      - "**"

defaults:
  run:
    shell: bash

jobs:
  depoy:
    name: Goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: "^1.13"

      - name: Release
        run: curl -sL https://git.io/goreleaser | bash
